### ISSUE TITLE
Palaeoecology links don't work

### ISSUE THREAD

**Issue by vladhc** [Pakillo/Rpackages_dir#1]
Both "Bchron Bayesian chronologies" and "Bclim Palaeoclimate reconstruction" open to 404 page.

**Comment by Pakillo** [comment]
Hi @vladhc,

Thanks for getting in touch. Yes, there are many packages for which I haven't set the link yet... including those you mention. I have now added the link for those two, and will try to keep updating the list from time to time. Meanwhile, googling the name of the package should take you directly to their CRAN or GitHub page.

Cheers,
Paco

**Comment by Pakillo** [comment]
Fixed now (see 62f3d7ed5eee1f028707bf9062a056ee5501ad92)
